#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ "$1" == "" ]; then
    echo "usage: gitvb-list-changed <branch>"
    exit 1
fi
branch="$1"


git diff --name-only $(git merge-base $MAIN_BRANCH origin/$MAIN_BRANCH)..$branch # | awk '{print $2}'
