#!/usr/bin/env bash
set -e

MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ ! -z "$(git diff --staged)" ]; then
    echo "there are staged changes. exiting."
    exit 1
fi

if [ "$(git branch --show-current)" != "$MAIN_BRANCH" ]; then
    echo "you are not on the main branch: $MAIN_BRANCH"
    exit 1
fi

if [ "$1" == "" ]; then
    echo "usage: gitvb-create <branch>"
    exit 1
fi

newBranch="$1"

if [ ! -z "$(git ls-remote --heads origin $newBranch)" ]; then
    echo "this branch already exists on the remote"
    exit 4
fi

gitvb-wip
git checkout "origin/$MAIN_BRANCH"
git checkout -b "$newBranch"
echo "HIT INTERNAL PUSH!"
BRANCH="$newBranch" PUSH_ARGS="-u origin $newBranch" gitvb-internal-push
git checkout "$MAIN_BRANCH"
gitvb-wip-undo
# $x/gitvb-pick "$newBranch"


echo
echo "successfully created $newBranch and uploaded it to origin!"
echo "  you can pick it by running"
echo "  $ gitvb-pick $newBranch"
echo
echo "  you can create an MR/PR using the link provided by the remote above"
echo
