#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ "$1" == "" ]; then
    echo "usage: gitvb-commit <branch>"
    exit 1
fi
branch="$1"

git diff --name-only origin/master..$branch # | awk '{print $2}'
