#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ -z "$1" ]; then
    echo "usage: gitvb-is-unpickable <branch>"
    exit 1
fi

# if you're unpicking you shouldn't have staged changes since we don't check your stage here
if [ ! -z "$(git diff --staged)" ]; then
    echo "there are staged changes. exiting."
    exit 1
fi


branch="$1"

files="$(git diff --name-only)"
picked="$(gitvb-ls)"
stashAdvice=""

if [ ! -z "$files" ]; then
    while IFS= read -r file; do
        # check what branch this file belongs to:
        while IFS= read -r branch; do
            if gitvb-is-changed-by-branch $file $branch 2> /dev/null; then
                echo
                echo "cannot unpick this. your working tree builds upon the work of one of your picked branches."
                echo "i.e. $file is modified on '$branch' but also in your tree"
                echo ""
                echo "if gitvb just blindly stashed the changes, they may not reapply onto the tree"
                echo "after unpicking this branch, so we can't safely do anything automatically."
                echo
                echo "current working tree includes:"
                gitvb-pretty-changelist "$(git diff --name-only)"
                echo 
                echo "the minimum to continue unpicking is:"
                echo ""
                echo "  $ git stash -m 'work on top of $branch' -- $file"
                echo ""
                echo "if you wish to continue unpicking"
                echo ""
                exit 1
            fi
        done <<< "$picked"
    done <<< "$files"

    echo "unpick lgtm!"
fi
