#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"
WIP_TOKEN=">>WIP<<"

if [ "$(git branch --show-current)" != "$MAIN_BRANCH" ]; then
    echo "you are not on the main branch: $MAIN_BRANCH"
    exit 1
fi

if [[ "$(git log -1 --pretty=%B)" == *"$WIP_TOKEN" ]]; then
    echo "WARNING: you have at least 1 WIP commit"
fi


echo ""
echo "picked:"
echo ""

gitvb-ls

# > verify all of the applied hashes are applied still
# > if not, warn
# git branch --contains 3add3e57a113b1aba30053298ff7f2c6ad3122fa

echo ""
echo "available:"
echo ""
# --no-merged HEAD 
branches="$(git branch -a --format='%(refname:short)' | sed "s/$MAIN_BRANCH//g")"
branchesLocal=$(echo "$branches" | grep -v '^origin/' || echo "none")
#  | sed 's/remotes\/origin\///g'

echo "$branchesLocal"
echo
