#!/usr/bin/env bash
set -e

MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ ! -z "$(git diff --staged)" ]; then
    echo "there are staged changes. exiting."
    exit 1
fi

if [ "$(git branch --show-current)" != "$MAIN_BRANCH" ]; then
    echo "you are not on the main branch: $MAIN_BRANCH"
    exit 1
fi

if [ "$1" == "" ]; then
    echo "usage: gitvb-create <branch>"
    exit 1
fi

newBranch="$1"

gitvb-wip
git checkout "origin/$MAIN_BRANCH"
git checkout -b "$newBranch"
git push -u origin "$newBranch"
git checkout "$MAIN_BRANCH"
gitvb-wip-undo
# $x/gitvb-pick "$newBranch"


echo
echo "succesfully created $newBranch and uploaded it to origin!"
echo "  you can pick it by running"
echo "  $ gitvb-pick $newBranch"
echo
echo "  you can create an MR/PR using the link provided by the remote above"
echo
