#!/usr/bin/env bash
set -e

FN="$(pwd)"
MAIN_BRANCH="main"

# todo bail if not on main branch

if [ "$1" == "" ]; then
    echo "usage: gitvb-create <branch>"
    exit 1
fi

newBranch="$1"

$FN/gitvb-wip
git checkout -b "$newBranch"
$FN/gitvb-wip-undo --hard
git push -u origin "$newBranch"
git checkout $MAIN_BRANCH
$FN/gitvb-wip-undo
# $x/gitvb-pick "$newBranch"