#!/usr/bin/env bash
# takes output from commands like "git diff --name-status" and makes them pretty
set -e
awk '
  $1 == "D" {print "\033[31m" "  -  " $2 "\033[0m"}
  $1 == "A" {print "\033[32m" "  +  " $2 "\033[0m"}
  $1 == "M" {print "\033[36m" "  ~  " $2 "\033[0m"}
'
