#!/usr/bin/env bash
set -e

MAIN_BRANCH="${MAIN_BRANCH:-main}"

# todo bail if not on main branch

if [ "$1" == "" ]; then
    echo "usage: gitvb-create <branch>"
    exit 1
fi

newBranch="$1"

gitvb-wip
# todo: safely branch from remote instead
git checkout -b "$newBranch"
gitvb-wip-undo --hard
git push -u origin "$newBranch"
git checkout $MAIN_BRANCH
gitvb-wip-undo
# $x/gitvb-pick "$newBranch"
