#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ ! -z "$(git diff --staged)" ]; then
    echo "there are staged changes. exiting."
    exit 1
fi

if [ "$(git branch --show-current)" != "$MAIN_BRANCH" ]; then
    echo "you are not on the main branch: $MAIN_BRANCH"
    exit 1
fi


if [ "$1" == "" ]; then
    echo "usage: gitvb-publish <branch>"
    exit 1
fi
publishBranch="$1"

vbFilePath="$GITVB_HOME/$publishBranch.gitvb"

if [ ! -f "$vbFilePath" ]; then
    echo "not picked $publishBranch"
    exit 2
fi

echo
echo "** need to resync before publishing!"
echo
gitvb-resync

echo
echo "** publishing your changes to $publishBranch"
echo
gitvb-wip
git checkout "$publishBranch"
git push --force-with-lease
git checkout "$MAIN_BRANCH"
gitvb-wip-undo

echo
echo "** succesfully published to $publishBranch"
echo
