#!/usr/bin/env bash
# for use with $1 of `git diff --name-only` or similar
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"
# USAGE="usage: gitvb-pretty-changelist <changelist>"

if [ "$1" == "" ]; then
    # echo ""
    exit 0
    # echo $USAGE
    # exit 1
fi

list="$1"
picked="$(gitvb-ls)"
extra="$2"

if [ ! -z "$list" ]; then
    while IFS= read -r file; do
        # echo "debug=$file"
        echo -n "$(git diff --name-status $extra -- $file | gitvb-pretty-status)  "
        set +e
        while IFS= read -r branch; do
            if [ ! -z "$branch" ]; then
                if gitvb-is-changed-by-branch $file $branch 2> /dev/null; then
                    echo -en "\033[90m"
                    echo -n "$branch "
                    echo -en "\033[0m"
                fi
            fi
        done <<< "$picked"
        set -e
        echo
    done <<< "$list"
fi
