#!/usr/bin/env bash
# send the contents of the stage directly to the remote where it belongs
set -e

if [ -z "$(git diff --staged)" ]; then
    echo "there are no staged changes"
    exit 1
fi

if [ "$1" == "" ]; then
    set +e
    branch="$(gitvb-determine-stage-branch 2> /dev/null)"
    set -e
else
    branch="$1"
fi

gitvb-commit $1
gitvb-publish $branch
gitvb-status
