#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
FN="$(pwd)"
MAIN_BRANCH="main"

MAX_REMOTE_LIST=10

echo "fetching remote..."
git fetch > /dev/null


echo ""
echo "picked:"
echo ""

$FN/gitvb-ls

# > verify all of the applied hashes are applied still
# > if not, warn
# git branch --contains 3add3e57a113b1aba30053298ff7f2c6ad3122fa

echo ""
echo "unpicked:"
echo ""
unmergedBranches="$(git branch -a --no-merged HEAD --format='%(refname:short)')"
branchesOnRemote=$(echo "$unmergedBranches" | grep '^origin/' || echo)
branchesLocal=$(echo "$unmergedBranches" | grep -v '^origin/' || echo)
#  | sed 's/remotes\/origin\///g'

echo "$branchesLocal"
# TODO: need to remove picked branches from here ?? ^

echo ""
echo "available:"
echo ""
echo "$branchesOnRemote" | head -n $MAX_REMOTE_LIST

nBranchesOnRemote=$(echo "$branchesOnRemote" | wc -l)
n2=$(echo "if ($nBranchesOnRemote > $MAX_REMOTE_LIST) $nBranchesOnRemote - $MAX_REMOTE_LIST else 0" | bc)

echo ...and $n2 more
echo
