#!/usr/bin/env bash
set -e

x="$(pwd)"
MAIN_BRANCH="master"

if [ "$1" == "" ]; then
    echo "usage: gitvb-create <branch>"
    exit 1
fi

newBranch="$1"

$x/gitvb-wip
git checkout -b "$newBranch"
git push -u origin "$newBranch"
git checkout $MAIN_BRANCH
$x/gitvb-pick "$newBranch"
$x/gitvb-wip-undo