#!/usr/bin/env bash
set -e

WIP_TOKEN=">>WIP<<"

# todo: do not continue if there are staged changes
echo "wip" >> .wip
git add .
git commit -m "[gitvb] work in progress - $(gitvb-ls | tr '\n' '+')

$WIP_TOKEN"
