#!/usr/bin/env bash
# send the contents of the stage directly to the remote where it belongs
set -e

if [ -z "$(git diff --staged)" ]; then
    echo "there are no staged changes"
    exit 1
fi

if [ "$1" == "" ]; then
    set +e
    branch="$(gitvb-determine-stage-branch 2> /dev/null)"
    set -e
else
    branch="$1"
fi

set +e
gitvb-sync-status
syncExit=$?
if [ "$syncExit" == "14" ]; then
    echo "should resync..."
    gitvb-resync
elif [ "$syncExit" == "0" ]; then
    echo "lgtm, does not need sync"
else
    echo "uh oh! - exit code: $syncExit"
    exit $syncExit
fi
set -e

gitvb-commit $1
gitvb-publish $branch
gitvb-status
