#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ "$(git branch --show-current)" != "$MAIN_BRANCH" ]; then
    echo "you are not on the main branch: $MAIN_BRANCH"
    exit 1
fi

if [ ! -z "$(git diff --staged)" ]; then
    echo "you have staged changes."
    echo "  commit with $ gitvb-commit <branch>."
    echo ""
fi

if [ "$1" == "" ]; then
    echo "usage: gitvb-pick-new <branch>"
    exit 1
fi
pickBranch="$1"

vbFilePath="$GITVB_HOME/$pickBranch.gitvb"

if [ -f "$vbFilePath" ]; then
    echo "cannot pick existing (and already picked) branch $pickBranch"
    exit 2
fi

gitvb-remote-create "$pickBranch"
gitvb-pick "$pickBranch"
