#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"

if [ ! -z "$(git diff --staged)" ]; then
    echo "there are staged changes. exiting."
    exit 1
fi

if [ "$(git branch --show-current)" != "$MAIN_BRANCH" ]; then
    echo "you are not on the main branch: $MAIN_BRANCH"
    exit 1
fi


if [ "$1" == "" ]; then
    echo "usage: gitvb-publish <branch>"
    exit 1
fi
publishBranch="$1"

vbFilePath="$GITVB_HOME/$publishBranch.gitvb"

if [ ! -f "$vbFilePath" ]; then
    echo "not picked $publishBranch"
    exit 2
fi

# if [ "$2" != "--no-resync" ]; then
#     echo
#     echo "** need to resync before publishing!"
#     echo
#     gitvb-resync
# fi

echo
echo "** publishing your changes to $publishBranch"
echo
gitvb-wip publish
git checkout "$publishBranch"

nRemote=$(git rev-list --count "origin/$publishBranch" ^"$publishBranch")
pushOutFile="$GITVB_HOME/$publishBranch.gitvb-push-msg"
echo "nRemote=$nRemote"
if [ "$nRemote" != "0" ]; then
    echo " (force required, remote not on $MAIN_BRANCH)"
    echo "force pushing..."
    BRANCH="$publishBranch" PUSH_ARGS="--force-with-lease" gitvb-internal-push
else 
    echo "pushing..."
    echo " (not using force)"
    BRANCH="$publishBranch" PUSH_ARGS="" gitvb-internal-push
fi

echo "publish: success, now checking out main branch..."
git checkout "$MAIN_BRANCH"
gitvb-wip-undo publish

echo
echo "** successfully published to $publishBranch"
echo
