#!/usr/bin/env bash
set -e

GITVB_HOME="./.git/.gitvb-v0"
MAIN_BRANCH="${MAIN_BRANCH:-main}"
STAGE_STASH_MSG="STAGED CHANGES FROM GITVB-PUBLISH-ALL"

stashedStage="0"
if [ ! -z "$(git diff --staged)" ]; then
    echo "WARNING: stashing the stage!"
    git stash --staged -m "$STAGE_STASH_MSG"
    stashedStage="1"
fi

gitvb-wip publish-all

if [ "$(git branch --show-current)" != "$MAIN_BRANCH" ]; then
    echo "you are not on the main branch: $MAIN_BRANCH"
    exit 1
fi

pickedBranches="$(gitvb-ls)"

git fetch --progress
nMainBehind=$(git rev-list --count $MAIN_BRANCH..origin/$MAIN_BRANCH)
if [ "$nMainBehind" != "0" ]; then
    echo
    echo "** you need to resync before publishing!"
    echo
    # gitvb-resync
    exit 1
fi

if [ ! -z "$pickedBranches" ]; then
    while IFS= read -r line; do
        if [ -z "$line" ]; then
            continue
        fi
        gitvb-publish "$line" --no-resync
    done <<< "$pickedBranches"
fi

gitvb-wip-undo publish-all

# undo the stage stash
if [ "$stashedStage" == "1" ]; then
    if [[ "$(git stash list)" == *$STAGE_STASH_MSG* ]]; then
        echo "Reapplying stash onto stage!"
        git stash pop --index # index pops onto the stage
    else 
        echo "oops, don't have expected stash for the stage!"
        exit 8
    fi
else
    echo "no stash to reapply back to stage"
fi


gitvb-status
